name: Build for Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: actions/checkout@v2
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --android=11.3

    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies with dotnet restore
      run: dotnet restore

    - name: Restore dependencies with nuget restore
      run: nuget restore

    - name: Build
      run: msbuild Vulcanova/Vulcanova.Android/Vulcanova.Android.csproj /t:PackageForAndroid /t:SignAndroidPackage /p:Configuration=Release
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: Vulcanova/Vulcanova.Android/bin/Release/com.companyname.Vulcanova-Signed.apk
